---
- hosts: all
  become: true
  tasks:
  - name: Update & upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install apache2
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
      state: latest 

  - name: Set Timezone to Africa/Lagos
    tags: time
    timezone: name=Africa/Lagos

  - name: Print Hostname on Server
    tags: printf
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html

  - name: Restart apache2
    tags: restart
    service:
      name: apache2
      state: restarted


      